[workspace]
members = [
    "oxide-llm",
    "oxide-llm-core",
    "oxide-llm-proto",
    "oxide-llm-transport",
    "oxide-llm-macros",
    "oxide-llm-executor",
    "examples/agent",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Shao G. <shaogme@gmail.com>"]
repository = "https://github.com/shaogme/oxide-llm"
description = ""
readme = "README.md"
homepage = "https://github.com/shaogme/oxide-llm"
documentation = "https://docs.rs/oxide-llm"
keywords = []
categories = []

[workspace.lints.rust]
warnings = "deny"

[workspace.dependencies]

# Internal Crates
oxide-llm = { path = "oxide-llm" }
oxide-llm-core = { path = "oxide-llm-core" }
oxide-llm-proto = { path = "oxide-llm-proto" }
oxide-llm-transport = { path = "oxide-llm-transport" }
oxide-llm-macros = { path = "oxide-llm-macros" }
oxide-llm-executor = { path = "oxide-llm-executor" }

# External Crates
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diagweave = "0.5.2"
ref_str = { version = "0.2", features = ["serde"] }

futures = "0.3.31"
bytes = "1.11.1"
trait-morph = "0.1.1"
