use ref_str::StaticRefStr;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

pub mod request;
pub mod response;

/// The base structured datatype containing multi-part content of a message.
///
/// 包含消息的多部分内容的基础结构化数据类型。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Content {
    /// Ordered `Parts` that constitute a single message.
    ///
    /// 构成单个消息的有序 `Parts`。
    pub parts: Vec<Part>,
    /// Optional. The producer of the content. Must be either 'user' or 'model'.
    ///
    /// 可选。内容的生产者。必须是 'user' 或 'model'。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<StaticRefStr>,
}

impl Content {
    pub fn user(parts: Vec<Part>) -> Self {
        Self {
            parts,
            role: Some("user".into()),
        }
    }

    pub fn model(parts: Vec<Part>) -> Self {
        Self {
            parts,
            role: Some("model".into()),
        }
    }
}

/// A datatype containing media that is part of a multi-part `Content` message.
///
/// 包含多部分 `Content` 消息一部分的媒体的数据类型。
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Part {
    /// Inline text.
    ///
    /// 内联文本。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,

    /// Inline media bytes.
    ///
    /// 内联媒体字节。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inline_data: Option<Blob>,

    /// A predicted [FunctionCall] returned from the model that contains
    /// a string representing the [FunctionDeclaration.name] with the
    /// arguments and their values.
    ///
    /// 模型返回的预测 [FunctionCall]，包含表示 [FunctionDeclaration.name] 的字符串以及参数及其值。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_call: Option<FunctionCall>,

    /// The result output of a [FunctionCall] that contains a string
    /// representing the [FunctionDeclaration.name] and a structured
    /// JSON object containing any output from the function call.
    ///
    /// [FunctionCall] 的结果输出，包含表示 [FunctionDeclaration.name] 的字符串和包含函数调用输出的结构化 JSON 对象。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_response: Option<FunctionResponse>,

    /// URI based data.
    ///
    /// 基于 URI 的数据。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_data: Option<FileData>,

    /// Code generated by the model that is meant to be executed.
    ///
    /// 模型生成的旨在执行的代码。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub executable_code: Option<ExecutableCode>,

    /// Result of executing the [ExecutableCode].
    ///
    /// 执行 [ExecutableCode] 的结果。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code_execution_result: Option<CodeExecutionResult>,

    /// Indicates if the part is thought content.
    ///
    /// 指示该部分是否为思考内容。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thought: Option<bool>,

    /// Signature of the thought content.
    ///
    /// 思考内容的签名。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thought_signature: Option<StaticRefStr>,

    /// Metadata for video content.
    ///
    /// 视频内容的元数据。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_metadata: Option<VideoMetadata>,

    /// Custom metadata associated with the Part.
    ///
    /// 与 Part 关联的自定义元数据。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_metadata: Option<serde_json::Value>,
}

impl Part {
    pub fn text(text: impl Into<String>) -> Self {
        Self {
            text: Some(text.into()),
            ..Default::default()
        }
    }
}

/// Metadata for video content.
///
/// 视频内容的元数据。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoMetadata {
    /// Start offset of the video.
    ///
    /// 视频的起始偏移量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_offset: Option<StaticRefStr>,

    /// End offset of the video.
    ///
    /// 视频的结束偏移量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_offset: Option<StaticRefStr>,
}

/// Raw media bytes.
///
/// 原始媒体字节。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Blob {
    /// The IANA standard MIME type of the source data.
    ///
    /// 源数据的 IANA 标准 MIME 类型。
    #[serde(rename = "mime_type")]
    pub mime_type: StaticRefStr,
    /// Raw bytes for media formats.
    ///
    /// 媒体格式的原始字节。
    pub data: StaticRefStr, // Base64 encoded string
}

/// A predicted [FunctionCall] returned from the model.
///
/// 模型返回的预测 [FunctionCall]。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCall {
    /// Optional. The unique id of the function call.
    ///
    /// 可选。函数调用的唯一 ID。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<StaticRefStr>,
    /// The name of the function to call.
    ///
    /// 要调用的函数的名称。
    pub name: StaticRefStr,
    /// The function parameters and values in JSON format.
    ///
    /// JSON 格式的函数参数和值。
    pub args: serde_json::Value,
}

/// The result output of a [FunctionCall].
///
/// [FunctionCall] 的结果输出。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionResponse {
    /// Optional. The id of the function call this response is for.
    ///
    /// 可选。此响应所针对的函数调用的 ID。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<StaticRefStr>,
    /// The name of the function to call.
    ///
    /// 要调用的函数的名称。
    pub name: StaticRefStr,
    /// The function response in JSON format.
    ///
    /// JSON 格式的函数响应。
    pub response: serde_json::Value,
    /// Optional. Ordered Parts that constitute a function response.
    ///
    /// 可选。构成函数响应的有序 Parts。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parts: Option<Vec<FunctionResponsePart>>,
    /// Optional. Signals that function call continues.
    ///
    /// 可选。表示函数调用继续。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub will_continue: Option<bool>,
    /// Optional. Specifies how the response should be scheduled.
    ///
    /// 可选。指定如何调度响应。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduling: Option<Scheduling>,
}

/// A datatype containing media that is part of a `FunctionResponse` message.
///
/// 包含 `FunctionResponse` 消息一部分的媒体的数据类型。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FunctionResponsePart {
    /// Inline media bytes.
    ///
    /// 内联媒体字节。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inline_data: Option<FunctionResponseBlob>,
}

/// Raw media bytes for function response.
///
/// 函数响应的原始媒体字节。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionResponseBlob {
    /// The IANA standard MIME type of the source data.
    ///
    /// 源数据的 IANA 标准 MIME 类型。
    #[serde(rename = "mime_type")]
    pub mime_type: StaticRefStr,
    /// Raw bytes for media formats.
    ///
    /// 媒体格式的原始字节。
    pub data: StaticRefStr, // Base64 encoded string
}

/// Specifies how the response should be scheduled in the conversation.
///
/// 指定如何在对话中调度响应。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Scheduling {
    SchedulingUnspecified,
    Silent,
    WhenIdle,
    Interrupt,
}

/// URI based data.
///
/// 基于 URI 的数据。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileData {
    /// Optional. The IANA standard MIME type of the source data.
    ///
    /// 可选。源数据的 IANA 标准 MIME 类型。
    #[serde(rename = "mime_type", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<StaticRefStr>,
    /// Required. The URI of the source data.
    ///
    /// 必填。源数据的 URI。
    #[serde(rename = "file_uri")]
    pub file_uri: StaticRefStr,
}

/// Code generated by the model that is meant to be executed.
///
/// 模型生成的旨在执行的代码。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutableCode {
    /// Required. The language of the code.
    ///
    /// 必填。代码的语言。
    pub language: CodeLanguage,
    /// Required. The code to be executed.
    ///
    /// 必填。要执行的代码。
    pub code: StaticRefStr,
}

/// Supported languages for code execution.
///
/// 代码执行支持的语言。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CodeLanguage {
    LanguageUnspecified,
    Python,
}

/// Result of executing the [ExecutableCode].
///
/// 执行 [ExecutableCode] 的结果。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CodeExecutionResult {
    /// Required. Outcome of the code execution.
    ///
    /// 必填。代码执行的结果。
    pub outcome: CodeExecutionOutcome,
    /// Optional. Contains stdout when code execution is successful, or
    /// stderr when code execution unsuccessful.
    ///
    /// 可选。代码执行成功时包含 stdout，或代码执行失败时包含 stderr。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output: Option<StaticRefStr>,
}

/// Outcome of the code execution.
///
/// 代码执行的结果。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CodeExecutionOutcome {
    OutcomeUnspecified,
    OutcomeOk,
    OutcomeFailed,
    OutcomeDeadlineExceeded,
}

/// The category of a rating.
///
/// 评分的类别。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum HarmCategory {
    HarmCategoryUnspecified,
    HarmCategoryDerogatory,
    HarmCategoryToxicity,
    HarmCategoryViolence,
    HarmCategorySexual,
    HarmCategoryMedical,
    HarmCategoryDangerous,
    HarmCategoryHarassment,
    HarmCategoryHateSpeech,
    HarmCategorySexuallyExplicit,
    HarmCategoryDangerousContent,
    HarmCategoryCivicIntegrity,
}

/// The probability that a piece of content is harmful.
///
/// 内容有害的概率。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum HarmProbability {
    HarmProbabilityUnspecified,
    Negligible,
    Low,
    Medium,
    High,
}

/// Block at and beyond a specified harm probability.
///
/// 在指定的伤害概率及以上进行阻止。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum HarmBlockThreshold {
    HarmBlockThresholdUnspecified,
    BlockLowAndAbove,
    BlockMediumAndAbove,
    BlockOnlyHigh,
    BlockNone,
    Off,
}

/// Content Part modality
///
/// 内容部分模态
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Modality {
    ModalityUnspecified,
    Text,
    Image,
    Video,
    Audio,
    Document,
}

/// A `Tool` is a piece of code that enables the system to interact with external systems.
///
/// `Tool` 原是一个代码片段，使系统能够与外部系统交互。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Tool {
    /// Optional. A list of `FunctionDeclarations` available to the `Model` that can be used for function calling.
    ///
    /// 可选。`Model` 可用于函数调用的 `FunctionDeclarations` 列表。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_declarations: Option<Vec<FunctionDeclaration>>,
    /// Optional. GoogleSearchRetrieval tool type.
    ///
    /// 可选。GoogleSearchRetrieval 工具类型。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub google_search_retrieval: Option<GoogleSearchRetrieval>,
    /// Optional. CodeExecution tool type.
    ///
    /// 可选。CodeExecution 工具类型。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code_execution: Option<CodeExecution>,
    /// Optional. GoogleSearch tool type.
    ///
    /// 可选。GoogleSearch 工具类型。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub google_search: Option<GoogleSearch>,
    /// Optional. Tool to support the model interacting directly with the computer.
    ///
    /// 可选。支持模型直接与计算机交互的工具。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub computer_use: Option<ComputerUse>,
    /// Optional. Tool to support URL context retrieval.
    ///
    /// 可选。支持 URL 上下文检索的工具。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url_context: Option<UrlContext>,
    /// Optional. FileSearch tool type.
    ///
    /// 可选。FileSearch 工具类型。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_search: Option<FileSearch>,
    /// Optional. Tool that allows grounding the model's response with geospatial context.
    ///
    /// 可选。允许使用地理空间上下文建立模型响应的工具。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub google_maps: Option<GoogleMaps>,
}

/// Structured representation of a function declaration.
///
/// 函数声明的结构化表示。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionDeclaration {
    /// Required. The name of the function.
    ///
    /// 必填。函数的名称。
    pub name: StaticRefStr,
    /// Required. A brief description of the function.
    ///
    /// 必填。函数的简要描述。
    pub description: StaticRefStr,
    /// Optional. Describes the parameters to this function.
    ///
    /// 可选。描述此函数的参数。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Schema>,
}

/// Tool configuration for any `Tool` specified in the request.
///
/// 请求中指定的任何 `Tool` 的工具配置。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolConfig {
    /// Optional. Function calling config.
    ///
    /// 可选。函数调用配置。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_calling_config: Option<FunctionCallingConfig>,
    /// Optional. Retrieval config.
    ///
    /// 可选。检索配置。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retrieval_config: Option<RetrievalConfig>,
}

/// Configuration for function calling.
///
/// 函数调用配置。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCallingConfig {
    /// Optional. Specifies the mode in which function calling should execute.
    ///
    /// 可选。指定函数调用应执行的模式。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<FunctionCallingConfigMode>,
    /// Optional. A set of function names that, when provided, limits the functions the model will call.
    ///
    /// 可选。一组函数名称，如果提供，将限制模型将调用的函数。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub allowed_function_names: Option<Vec<StaticRefStr>>,
}

/// Defines the execution mode for function calling.
///
/// 定义函数调用的执行模式。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum FunctionCallingConfigMode {
    ModeUnspecified,
    Auto,
    Any,
    None,
}

/// Tool to retrieve information from Google Search.
///
/// 从 Google 搜索检索信息的工具。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GoogleSearchRetrieval {
    /// Optional. Specifies the dynamic retrieval configuration for the given source.
    ///
    /// 可选。指定给定源的动态检索配置。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dynamic_retrieval_config: Option<DynamicRetrievalConfig>,
}

/// Describes the dynamic retrieval configuration for the given source.
///
/// 描述给定源的动态检索配置。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DynamicRetrievalConfig {
    /// Optional. The mode of the dynamic retrieval.
    ///
    /// 可选。动态检索的模式。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<DynamicRetrievalMode>,
    /// Optional. The threshold to be used for dynamic retrieval.
    ///
    /// 可选。用于动态检索的阈值。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dynamic_threshold: Option<f32>,
}

/// The mode of the dynamic retrieval.
///
/// 动态检索的模式。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DynamicRetrievalMode {
    ModeUnspecified,
    ModeDynamic,
}

/// Tool that enables the model to execute code as part of generation.
///
/// 使模型能够作为生成的一部分执行代码的工具。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CodeExecution {}

/// GoogleSearch tool type.
///
/// GoogleSearch 工具类型。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GoogleSearch {
    /// Optional. Filter search results to a specific time range.
    ///
    /// 可选。将搜索结果过滤到特定时间范围。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_range_filter: Option<Interval>,
}

/// Represents a time interval.
///
/// 表示时间间隔。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Interval {
    /// Optional. Inclusive start of the interval.
    ///
    /// 可选。间隔的起始（包含）。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_time: Option<StaticRefStr>,
    /// Optional. Exclusive end of the interval.
    ///
    /// 可选。间隔的结束（不包含）。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_time: Option<StaticRefStr>,
}

/// Computer Use tool type.
///
/// 计算机使用工具类型。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ComputerUse {
    /// Required. The environment being operated.
    ///
    /// 必填。正在操作的环境。
    pub environment: Environment,
    /// Optional. By default, predefined functions are included in the final model call.
    ///
    /// 可选。默认情况下，预定义函数包含在最终模型调用中。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub excluded_predefined_functions: Option<Vec<StaticRefStr>>,
}

/// Represents the environment being operated, such as a web browser.
///
/// 表示正在操作的环境，例如 Web 浏览器。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Environment {
    EnvironmentUnspecified,
    EnvironmentBrowser,
}

/// Tool to support URL context retrieval.
///
/// 支持 URL 上下文检索的工具。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UrlContext {}

/// The FileSearch tool that retrieves knowledge from Semantic Retrieval corpora.
///
/// 从语义检索语料库检索知识的 FileSearch 工具。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileSearch {
    /// Required. The names of the fileSearchStores to retrieve from.
    ///
    /// 必填。要从中检索的 fileSearchStores 的名称。
    pub file_search_store_names: Vec<StaticRefStr>,
    /// Optional. Metadata filter to apply to the semantic retrieval documents and chunks.
    ///
    /// 可选。应用于语义检索文档和块的元数据过滤器。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata_filter: Option<StaticRefStr>,
    /// Optional. The number of semantic retrieval chunks to retrieve.
    ///
    /// 可选。要检索的语义检索块的数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_k: Option<i32>,
}

/// The GoogleMaps Tool that provides geospatial context for the user's query.
///
/// 为用户查询提供地理空间上下文的 GoogleMaps 工具。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GoogleMaps {
    /// Optional. Whether to return a widget context token in the GroundingMetadata.
    ///
    /// 可选。是否在 GroundingMetadata 中返回小部件上下文令牌。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enable_widget: Option<bool>,
}

/// Retrieval config.
///
/// 检索配置。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RetrievalConfig {
    /// Optional. The location of the user.
    ///
    /// 可选。用户的位置。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lat_lng: Option<LatLng>,
    /// Optional. The language code of the user.
    ///
    /// 可选。用户的语言代码。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language_code: Option<StaticRefStr>,
}

/// An object that represents a latitude/longitude pair.
///
/// 表示纬度/经度对的对象。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LatLng {
    /// The latitude in degrees.
    ///
    /// 纬度（度）。
    pub latitude: f64,
    /// The longitude in degrees.
    ///
    /// 经度（度）。
    pub longitude: f64,
}

/// The Schema object allows the definition of input and output data types.
/// These types can be objects, but also primitives and arrays.
/// Represents a subset of the [OpenAPI schema](https://spec.openapis.org/oas/v3.0.3#schema).
///
/// Schema 对象允许定义输入和输出数据类型。
/// 这些类型可以是对象，也可以是基元和数组。
/// 表示 [OpenAPI 模式](https://spec.openapis.org/oas/v3.0.3#schema) 的子集。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Schema {
    /// Required. Data type.
    ///
    /// 必填。数据类型。
    #[serde(rename = "type")]
    pub schema_type: Type,
    /// Optional. The format of the data.
    ///
    /// 可选。数据的格式。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub format: Option<StaticRefStr>,
    /// Optional. A brief description of the parameter.
    ///
    /// 可选。参数的简要说明。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<StaticRefStr>,
    /// Optional. Indicates if the value may be null.
    ///
    /// 可选。指示该值是否可以为 null。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nullable: Option<bool>,
    /// Optional. Possible values of the element of Type.STRING with enum format.
    ///
    /// 可选。Type.STRING 类型的元素以及枚举格式的可能值。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#enum: Option<Vec<StaticRefStr>>,
    /// Optional. Properties of Type.OBJECT.
    ///
    /// 可选。Type.OBJECT 的属性。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub properties: Option<HashMap<StaticRefStr, Schema>>,
    /// Optional. Required properties of Type.OBJECT.
    ///
    /// 可选。Type.OBJECT 的必需属性。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub required: Option<Vec<StaticRefStr>>,
    /// Optional. Schema of the elements of Type.ARRAY.
    ///
    /// 可选。Type.ARRAY 元素的架构。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub items: Option<Box<Schema>>,
}

/// Type contains the list of OpenAPI data types as defined by [OpenAPI schema](https://spec.openapis.org/oas/v3.0.3#schema).
///
/// Type 包含 [OpenAPI 模式](https://spec.openapis.org/oas/v3.0.3#schema) 定义的 OpenAPI 数据类型列表。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Type {
    TypeUnspecified,
    String,
    Number,
    Integer,
    Boolean,
    Array,
    Object,
}

/// Metadata on the generation request's token usage.
///
/// 关于生成请求的令牌使用的元数据。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UsageMetadata {
    /// Number of tokens in the prompt.
    ///
    /// 提示中的令牌数。
    #[serde(default)]
    pub prompt_token_count: i32,
    /// Number of tokens in the cached part of the prompt (the cached content).
    ///
    /// 提示的缓存部分（缓存内容）中的令牌数。
    #[serde(default)]
    pub cached_content_token_count: i32,
    /// Total number of tokens across all the generated response candidates.
    ///
    /// 所有生成的响应候选项的令牌总数。
    #[serde(default)]
    pub candidates_token_count: i32,
    /// Output only. Number of tokens present in tool-use prompt(s).
    ///
    /// 仅输出。工具使用提示中存在的令牌数。
    #[serde(default)]
    pub tool_use_prompt_token_count: i32,
    /// Output only. Number of tokens of thoughts for thinking models.
    ///
    /// 仅输出。思考模型的思考令牌数。
    #[serde(default)]
    pub thoughts_token_count: i32,
    /// 生成请求（提示 + 响应候选项）的总令牌数。
    #[serde(default)]
    pub total_token_count: i32,
    /// Output only. List of modalities that were processed in the request input.
    ///
    /// 仅输出。请求输入中处理的模态列表。
    #[serde(default)]
    pub prompt_tokens_details: Vec<ModalityTokenCount>,
    /// Output only. List of modalities of the cached content in the request input.
    ///
    /// 仅输出。请求输入中缓存内容的模态列表。
    #[serde(default)]
    pub cache_tokens_details: Vec<ModalityTokenCount>,
    /// Output only. List of modalities that were returned in the response.
    ///
    /// 仅输出。响应中返回的模态列表。
    #[serde(default)]
    pub candidates_tokens_details: Vec<ModalityTokenCount>,
    /// Output only. List of modalities that were processed for tool-use request inputs.
    ///
    /// 仅输出。为工具使用请求输入处理的模态列表。
    #[serde(default)]
    pub tool_use_prompt_tokens_details: Vec<ModalityTokenCount>,
}

/// Represents token counting info for a single modality.
///
/// 表示单个模态的令牌计数信息。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModalityTokenCount {
    /// The modality associated with this token count.
    ///
    /// 与此令牌计数关联的模态。
    pub modality: Modality,
    /// Number of tokens.
    ///
    /// 令牌数量。
    pub token_count: i32,
}

/// Metadata on the usage of the cached content.
///
/// 以前存内容的使用的元数据。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CachedContentUsageMetadata {
    /// Total number of tokens that the cached content consumes.
    ///
    /// 缓存内容消耗的令牌总数。
    pub total_token_count: i32,
}

/// Cached content resource.
///
/// 缓存的内容资源。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CachedContent {
    /// Optional. Input only. Immutable. The content to cache.
    ///
    /// 可选。仅输入。不可变。要缓存的内容。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contents: Option<Vec<Content>>,
    /// Optional. Input only. Immutable. A list of `Tools` the model may use to generate the next response.
    ///
    /// 可选。仅输入。不可变。模型可能用于生成下一个响应的 `Tools` 列表。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<Tool>>,
    /// Optional. Timestamp in UTC of when this resource is considered expired.
    ///
    /// 可选。此资源被视为过期的 UTC 时间戳。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expire_time: Option<StaticRefStr>,
    /// Optional. Input only. New TTL for this resource, input only.
    ///
    /// 可选。仅输入。此资源的新 TTL，仅输入。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ttl: Option<StaticRefStr>,
    /// Optional. Immutable. The user-generated meaningful display name of the cached content.
    ///
    /// 可选。不可变。用户生成的缓存内容有意义的显示名称。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_name: Option<StaticRefStr>,
    /// Required. Immutable. The name of the `Model` to use for cached content.
    ///
    /// 必填。不可变。用于缓存内容的 `Model` 名称。
    pub model: StaticRefStr,
    /// Optional. Input only. Immutable. Developer set system instruction.
    ///
    /// 可选。仅输入。不可变。开发者设置的系统指令。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_instruction: Option<Content>,
    /// Optional. Input only. Immutable. Tool config.
    ///
    /// 可选。仅输入。不可变。工具配置。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_config: Option<ToolConfig>,
    /// Output only. The resource name referring to the content cache entry.
    ///
    /// 仅输出。引用内容缓存条目的资源名称。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<StaticRefStr>,
    /// Output only. Creation time of the cache.
    ///
    /// 仅输出。缓存的创建时间。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_time: Option<StaticRefStr>,
    /// Output only. Update time of the cache.
    ///
    /// 仅输出。缓存的更新时间。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_time: Option<StaticRefStr>,
    /// Output only. Metadata on the token usage.
    ///
    /// 仅输出。令牌使用的元数据。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage_metadata: Option<CachedContentUsageMetadata>,
}
