use serde::{Deserialize, Serialize};

use super::container::Container;
use super::content::{ContentBlock, Role};

/// Response object for the Messages API.
///
/// Messages API 的响应对象。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessagesResponse {
    /// Unique object identifier.
    ///
    /// 唯一的对象标识符。
    pub id: String,

    /// Object type ("message").
    ///
    /// 对象类型（固定为 "message"）。
    #[serde(rename = "type")]
    pub r#type: String,

    /// Conversational role of the generated message (always "assistant").
    ///
    /// 生成消息的对话角色（固定为 "assistant"）。
    pub role: Role,

    /// Content generated by the model.
    ///
    /// 模型生成的内容。
    pub content: Vec<ContentBlock>,

    /// The model that handled the request.
    ///
    /// 处理请求的模型。
    pub model: String,

    /// Information about the container used in the request.
    ///
    /// 请求中使用的容器信息。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub container: Option<Container>,

    /// The reason that the model stopped generating.
    ///
    /// 模型停止生成的原因。
    pub stop_reason: Option<StopReason>,

    /// Which custom stop sequence was generated, if any.
    ///
    /// 生成的自定义停止序列（如果有）。
    pub stop_sequence: Option<String>,

    /// Billing and rate-limit usage.
    ///
    /// 计费和速率限制使用情况。
    pub usage: Usage,
}

/// The reason the model stopped generating content.
///
/// 模型停止生成内容的原因。
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    /// The model reached a natural stopping point.
    ///
    /// 模型到达自然的停止点。
    EndTurn,

    /// The maximum number of tokens specified in the request was reached.
    ///
    /// 达到了请求中指定的最大 token 数量。
    MaxTokens,

    /// One of your provided custom stop sequences was generated.
    ///
    /// 生成了你提供的自定义停止序列之一。
    StopSequence,

    /// The model invoked one or more tools.
    ///
    /// 模型调用了一个或多个工具。
    ToolUse,

    /// The turn was paused.
    ///
    /// 对话轮次已被暂停。
    PauseTurn,

    /// The model refused to answer the prompt.
    ///
    /// 模型拒绝回答提示词。
    Refusal,
}

/// Billing and rate-limit usage information.
///
/// 计费和速率限制使用情况信息。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Usage {
    /// The number of input tokens which were used.
    ///
    /// 使用的输入 token 数量。
    pub input_tokens: u32,

    /// The number of output tokens which were used.
    ///
    /// 使用的输出 token 数量。
    pub output_tokens: u32,

    /// The number of input tokens used to create the cache entry.
    ///
    /// 用于创建缓存条目的输入 token 数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_creation_input_tokens: Option<u32>,

    /// The number of input tokens read from the cache.
    ///
    /// 从缓存读取的输入 token 数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_read_input_tokens: Option<u32>,

    /// Breakdown of cached tokens by TTL.
    ///
    /// 按 TTL 细分的缓存创建使用情况。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_creation: Option<CacheCreation>,

    /// The geographic region where inference was performed for this request.
    ///
    /// 执行此请求推理的地理区域。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inference_geo: Option<String>,

    /// Breakdown of output tokens by category.
    ///
    /// 按类别细分的输出 token 详情。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_tokens_details: Option<OutputTokensDetails>,

    /// Server-side tool usage breakdown.
    ///
    /// 服务端工具使用情况细分。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub server_tool_use: Option<ServerToolUse>,

    /// The service tier used for the request.
    ///
    /// 请求使用的服务层级。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<ServiceTier>,
}

/// Breakdown of cached tokens by TTL (Time-to-Live).
///
/// 按 TTL（生存时间）细分的缓存 token 数量。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CacheCreation {
    /// The number of input tokens used to create the 1 hour cache entry.
    ///
    /// 用于创建 1 小时缓存条目的输入 token 数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ephemeral_1h_input_tokens: Option<u32>,

    /// The number of input tokens used to create the 5 minute cache entry.
    ///
    /// 用于创建 5 分钟缓存条目的输入 token 数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ephemeral_5m_input_tokens: Option<u32>,
}

/// Breakdown of output tokens by category.
///
/// 按类别细分的输出 token 详情。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutputTokensDetails {
    /// Number of output tokens the model generated as internal reasoning.
    ///
    /// 模型作为内部推理生成的输出 token 数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking_tokens: Option<u32>,
}

/// The number of server tool requests used.
///
/// 服务端工具请求的使用数量。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerToolUse {
    /// The number of web fetch tool requests.
    ///
    /// Web 获取工具请求的数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub web_fetch_requests: Option<u32>,

    /// The number of web search tool requests.
    ///
    /// Web 搜索工具请求的数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub web_search_requests: Option<u32>,
}

/// Service tier used for the request.
///
/// 请求使用的服务层级。
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ServiceTier {
    /// Standard tier.
    ///
    /// 标准层级。
    Standard,

    /// Priority tier.
    ///
    /// 优先层级。
    Priority,

    /// Batch tier.
    ///
    /// 批处理层级。
    Batch,
}
