use super::{LogProbs, ToolCall};
use ref_str::StaticRefStr;
use serde::{Deserialize, Serialize};

/// Represents a chat completion response returned by model, based on the provided input.
///
/// 表示模型根据提供的输入返回的聊天补全响应。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionResponse {
    /// A unique identifier for the chat completion.
    ///
    /// 聊天补全的唯一标识符。
    pub id: String,

    /// The object type, which is always `chat.completion`.
    ///
    /// 对象类型，固定为 `chat.completion`。
    pub object: String,

    /// The Unix timestamp (in seconds) of when the chat completion was created.
    ///
    /// 聊天补全创建时的 Unix 时间戳（秒）。
    pub created: i64,

    /// The model used for the chat completion.
    ///
    /// 用于聊天补全的模型。
    pub model: String,

    /// A list of chat completion choices.
    ///
    /// 聊天补全选项列表。
    pub choices: Vec<ChatCompletionChoice>,

    /// Usage statistics for the completion request.
    ///
    /// 补全请求的用量统计。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<CompletionUsage>,

    /// This fingerprint represents the backend configuration that the model runs with.
    ///
    /// 代表模型运行的后端配置指纹。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_fingerprint: Option<String>,

    /// The service tier used for processing the request.
    ///
    /// 用于处理请求的服务层级。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<String>,
}

/// A completion choice generated by the model.
///
/// 模型生成的补全选项。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionChoice {
    /// The index of the choice in the list of choices.
    ///
    /// 该选项在选项列表中的索引。
    pub index: u32,

    /// A chat completion message generated by the model.
    ///
    /// 模型生成的聊天补全消息。
    pub message: ChatCompletionResponseMessage,

    /// Log probability information for the choice.
    ///
    /// 选项的对数概率信息。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<LogProbs>,

    /// The reason the model stopped generating tokens.
    ///
    /// 模型停止生成词元的原因。
    pub finish_reason: String,
}

/// A chat completion message generated by the model.
///
/// 模型生成的聊天补全消息。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessage {
    /// The role of the author of this message.
    ///
    /// 消息作者的角色。
    pub role: String,

    /// The contents of the message.
    ///
    /// 消息文本内容。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    /// The refusal message generated by the model.
    ///
    /// 模型生成的拒绝回答信息。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub refusal: Option<StaticRefStr>,

    /// Annotations for the message, when applicable (e.g., web search URL citations).
    ///
    /// 消息的标注信息（例如网络搜索 URL 引用）。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub annotations: Option<Vec<Annotation>>,

    /// The tool calls generated by the model.
    ///
    /// 模型生成的工具调用列表。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,

    /// Audio response data if audio output modality was requested.
    ///
    /// 当请求音频输出模式时的音频响应数据。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audio: Option<AudioResponse>,

    /// Deprecated function call generated by the model.
    ///
    /// 模型生成的函数调用（已废弃）。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_call: Option<FunctionCall>,
}

/// Annotations for a message.
///
/// 消息的标注信息。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Annotation {
    /// A URL citation when using web search.
    ///
    /// 使用网络搜索时的 URL 引用。
    UrlCitation { url_citation: UrlCitation },
}

/// A URL citation when using web search.
///
/// 网络搜索时的 URL 引用对象。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UrlCitation {
    /// The index of the first character of the URL citation in the message.
    ///
    /// URL 引用在消息中的起始字符索引。
    pub start_index: u32,

    /// The index of the last character of the URL citation in the message.
    ///
    /// URL 引用在消息中的结束字符索引。
    pub end_index: u32,

    /// The URL of the web resource.
    ///
    /// 网络资源的 URL 地址。
    pub url: String,

    /// The title of the web resource.
    ///
    /// 网络资源的标题。
    pub title: String,
}

/// Audio response data generated by the model.
///
/// 模型生成的音频响应数据。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AudioResponse {
    /// Unique identifier for this audio response.
    ///
    /// 此音频响应的唯一标识符。
    pub id: String,

    /// Unix timestamp (in seconds) for when this audio response expires.
    ///
    /// 音频响应过期的 Unix 时间戳（秒）。
    pub expires_at: i64,

    /// Base64 encoded audio bytes generated by the model.
    ///
    /// 模型生成的 Base64 编码音频数据。
    pub data: StaticRefStr,

    /// Transcript of the audio generated by the model.
    ///
    /// 模型生成的音频文本转录。
    pub transcript: String,
}

/// Function call generated by the model (deprecated).
///
/// 模型生成的函数调用（已废弃）。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCall {
    /// The name of the function to call.
    ///
    /// 要调用的函数名称。
    pub name: String,

    /// The arguments to call the function with, in JSON format.
    ///
    /// 调用函数传入的参数（JSON 字符串格式）。
    pub arguments: String,
}

/// Usage statistics for the completion request.
///
/// 补全请求的用量统计信息。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionUsage {
    /// Number of tokens in the prompt.
    ///
    /// 提示词中的词元数量。
    pub prompt_tokens: u32,

    /// Number of tokens in the generated completion.
    ///
    /// 生成的补全中的词元数量。
    pub completion_tokens: u32,

    /// Total number of tokens used in the request (prompt + completion).
    ///
    /// 请求中使用的词元总数（提示词 + 补全）。
    pub total_tokens: u32,

    /// Breakdown of tokens used to generate the completion.
    ///
    /// 生成补全时使用的词元详细分解。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completion_tokens_details: Option<CompletionTokensDetails>,

    /// Breakdown of tokens used in the prompt.
    ///
    /// 提示词中使用的词元详细分解。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_tokens_details: Option<PromptTokensDetails>,
}

/// Breakdown of tokens used to generate the completion.
///
/// 生成补全时使用的词元详细分解信息。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionTokensDetails {
    /// Number of accepted prediction tokens.
    ///
    /// 被接受的预测词元数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub accepted_prediction_tokens: Option<u32>,

    /// Audio tokens generated by the model.
    ///
    /// 模型生成的音频词元数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audio_tokens: Option<u32>,

    /// Tokens generated by the model for reasoning.
    ///
    /// 模型用于推理而生成的词元数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_tokens: Option<u32>,

    /// Number of rejected prediction tokens.
    ///
    /// 被拒绝的预测词元数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rejected_prediction_tokens: Option<u32>,
}

/// Breakdown of tokens used in the prompt.
///
/// 提示词中使用的词元详细分解信息。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromptTokensDetails {
    /// Audio input tokens present in the prompt.
    ///
    /// 提示词中包含的音频输入词元数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audio_tokens: Option<u32>,

    /// Cached tokens present in the prompt.
    ///
    /// 提示词中包含的缓存词元数量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cached_tokens: Option<u32>,
}
