use ref_str::StaticRefStr;
use serde::{Deserialize, Serialize};

/// Definition of a function tool that the model can call.
///
/// 模型可以调用的函数工具定义。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionDefinition {
    /// The name of the function to be called.
    ///
    /// 要调用的函数名称。
    pub name: StaticRefStr,

    /// A description of what the function does.
    ///
    /// 函数的功能描述。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<StaticRefStr>,

    /// The parameters the function accepts, described as a JSON Schema object.
    ///
    /// 函数接受的参数，以 JSON Schema 对象形式描述。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,

    /// Whether to enable strict schema adherence when generating the function call.
    ///
    /// 生成函数调用时是否启用严格模式以遵循 Schema。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Function details used when forcing a specific function tool choice.
///
/// 强制选择特定函数工具时使用的函数详情。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolChoiceFunction {
    /// The name of the function to call.
    ///
    /// 要调用的函数名称。
    pub name: StaticRefStr,
}

/// A tool the model may call during chat completion.
///
/// 模型在聊天补全期间可能调用的工具。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tool {
    /// The type of the tool (e.g., "function" or "custom").
    ///
    /// 工具类型（例如 "function" 或 "custom"）。
    pub r#type: StaticRefStr,

    /// Function object details when type is "function".
    ///
    /// 当类型为 "function" 时的函数对象详情。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function: Option<FunctionDefinition>,

    /// Custom tool details when type is "custom".
    ///
    /// 当类型为 "custom" 时的自定义工具详情。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom: Option<CustomToolDefinition>,
}

/// Definition of a custom tool.
///
/// 自定义工具的定义。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustomToolDefinition {
    /// The name of the custom tool.
    ///
    /// 自定义工具的名称。
    pub name: StaticRefStr,

    /// Description of what the custom tool does.
    ///
    /// 自定义工具的功能描述。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<StaticRefStr>,

    /// Parameters for the custom tool as JSON Schema.
    ///
    /// 自定义工具的 JSON Schema 参数。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

/// Controls which (if any) tool is called by the model.
///
/// 控制模型调用哪个（如果有）工具。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ToolChoice {
    /// A simple string option: "none", "auto", or "required".
    ///
    /// 简单字符串选项："none"、"auto" 或 "required"。
    String(StaticRefStr),

    /// A specific named tool selection.
    ///
    /// 指定名称的工具选择。
    Named(ToolChoiceNamed),

    /// A selection of allowed tools with a mode.
    ///
    /// 包含模式的允许工具集选择。
    Allowed(ToolChoiceAllowedChoice),
}

/// A specific tool choice by name and type.
///
/// 按名称和类型指定的工具选择。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolChoiceNamed {
    /// The type of tool ("function" or "custom").
    ///
    /// 工具类型（"function" 或 "custom"）。
    pub r#type: StaticRefStr,

    /// Function choice details when type is "function".
    ///
    /// 当类型为 "function" 时的函数选择详情。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function: Option<ToolChoiceFunction>,

    /// Custom tool choice details when type is "custom".
    ///
    /// 当类型为 "custom" 时的自定义工具选择详情。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom: Option<ToolChoiceCustom>,
}

/// Custom tool choice details.
///
/// 自定义工具选择详情。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolChoiceCustom {
    /// The name of the custom tool to call.
    ///
    /// 要调用的自定义工具名称。
    pub name: StaticRefStr,
}

/// Choice configuration for restricting allowed tools.
///
/// 限制允许调用的工具配置选择。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolChoiceAllowedChoice {
    /// The type discriminator, should be "allowed_tools".
    ///
    /// 类型标识符，应为 "allowed_tools"。
    pub r#type: StaticRefStr,

    /// Allowed tools configuration.
    ///
    /// 允许调用的工具配置。
    pub allowed_tools: AllowedTools,
}

/// Allowed tools configuration details.
///
/// 允许调用的工具配置详情。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AllowedTools {
    /// Tool selection mode ("auto" or "required").
    ///
    /// 工具选择模式（"auto" 或 "required"）。
    pub mode: StaticRefStr,

    /// List of allowed tool specifications.
    ///
    /// 允许调用的工具规范列表。
    pub tools: Vec<serde_json::Value>,
}

/// A tool call generated by the model.
///
/// 模型生成的工具调用。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// The unique identifier of the tool call.
    ///
    /// 工具调用的唯一标识符。
    pub id: StaticRefStr,

    /// The type of the tool (e.g., "function" or "custom").
    ///
    /// 工具类型（例如 "function" 或 "custom"）。
    pub r#type: StaticRefStr,

    /// The function that the model called (present when type is "function").
    ///
    /// 模型调用的函数（类型为 "function" 时存在）。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function: Option<ToolCallFunction>,

    /// The custom tool that the model called (present when type is "custom").
    ///
    /// 模型调用的自定义工具（类型为 "custom" 时存在）。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom: Option<ToolCallCustom>,
}

/// Function details within a tool call.
///
/// 工具调用中的函数详情。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallFunction {
    /// The name of the function called.
    ///
    /// 被调用的函数名称。
    pub name: StaticRefStr,

    /// The arguments to call the function with, in JSON format string.
    ///
    /// 调用函数时传入的参数（JSON 字符串格式）。
    pub arguments: StaticRefStr,
}

/// Custom tool details within a tool call.
///
/// 工具调用中的自定义工具详情。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallCustom {
    /// The name of the custom tool called.
    ///
    /// 被调用的自定义工具名称。
    pub name: StaticRefStr,

    /// Input payload for the custom tool.
    ///
    /// 传递给自定义工具的输入载荷。
    pub input: StaticRefStr,
}
