[package]
name = "agent"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
oxide-llm = { workspace = true, features = ["transport-reqwest"] }

toml = "0.8"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.6", features = ["derive"] }
futures.workspace = true
serde.workspace = true
diagweave.workspace = true

[lints]
workspace = true
