[package]
name = "oxide-llm-transport"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest"]

[dependencies]
serde.workspace = true

oxide-llm-core.workspace = true

bytes.workspace = true
futures.workspace = true

[dependencies.reqwest]
version = "0.12.12"
features = ["json", "stream"]
optional = true
