use super::{LogProbs, response::CompletionUsage};
use ref_str::StaticRefStr;
use serde::{Deserialize, Serialize};

/// Represents a streamed chunk of a chat completion response returned by the model.
///
/// 表示由模型返回的聊天补全响应的流式 Chunk 块。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionChunk {
    /// A unique identifier for the chat completion. Each chunk has the same ID.
    ///
    /// 聊天补全的唯一标识符。每个 Chunk 具有相同的 ID。
    pub id: StaticRefStr,

    /// The object type, which is always `chat.completion.chunk`.
    ///
    /// 对象类型，固定为 `chat.completion.chunk`。
    pub object: StaticRefStr,

    /// The Unix timestamp (in seconds) of when the chat completion was created.
    ///
    /// 聊天补全创建时的 Unix 时间戳（秒）。
    pub created: i64,

    /// The model to generate the completion.
    ///
    /// 用于生成补全的模型名称。
    pub model: StaticRefStr,

    /// Specifies the latency tier to use for processing the request.
    ///
    /// 用于处理请求的服务层级。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<StaticRefStr>,

    /// This fingerprint represents the backend configuration that the model runs with.
    ///
    /// 代表模型运行的后端配置指纹。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_fingerprint: Option<StaticRefStr>,

    /// A list of chat completion choices.
    ///
    /// 聊天补全选项列表。
    pub choices: Vec<ChatCompletionChunkChoice>,

    /// An optional field containing token usage statistics for the entire request (present on the last chunk when stream_options.include_usage is true).
    ///
    /// 可选的 token 用量统计信息（当 stream_options.include_usage 为 true 时在最后一个 Chunk 中提供）。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<CompletionUsage>,
}

/// A choice in a streamed chat completion chunk.
///
/// 流式聊天补全 Chunk 中的单条选项。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionChunkChoice {
    /// The index of the choice in the list of choices.
    ///
    /// 该选项在选项列表中的索引。
    pub index: u32,

    /// A chat completion delta generated by streamed model responses.
    ///
    /// 流式模型响应生成的聊天补全增量数据。
    pub delta: ChatCompletionChunkDelta,

    /// Log probability information for the choice.
    ///
    /// 选项的对数概率信息。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<LogProbs>,

    /// The reason the model stopped generating tokens.
    ///
    /// 模型停止生成词元的原因。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<FinishReason>,
}

/// The reason the model stopped generating tokens.
///
/// 模型停止生成词元的原因。
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum FinishReason {
    /// The model hit a natural stop point or a provided stop sequence.
    ///
    /// 模型到达自然停止点或提供的停止序列。
    Stop,

    /// The maximum number of tokens specified in the request was reached.
    ///
    /// 达到了请求中指定的最大 token 数量。
    Length,

    /// The model called a tool.
    ///
    /// 模型调用了工具。
    ToolCalls,

    /// Content was omitted due to a flag from content filters.
    ///
    /// 内容因内容过滤器被省略。
    ContentFilter,

    /// The model called a function (deprecated).
    ///
    /// 模型调用了函数（已废弃）。
    FunctionCall,
}

/// A chat completion delta generated by streamed model responses.
///
/// 由流式模型响应生成的聊天补全增量内容。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionChunkDelta {
    /// The role of the author of this message.
    ///
    /// 消息作者的角色。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<StaticRefStr>,

    /// The contents of the chunk message.
    ///
    /// Chunk 消息文本内容。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    /// Reasoning content generated by reasoning models (e.g. o1/o3 series).
    ///
    /// 推理模型（如 o1/o3 系列）生成的推理思考内容。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_content: Option<String>,

    /// Tool call chunk objects generated by the model.
    ///
    /// 模型生成的工具调用 Chunk 对象列表。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ChatCompletionChunkToolCall>>,

    /// Function call chunk generated by the model (deprecated).
    ///
    /// 模型生成的函数调用 Chunk（已废弃）。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_call: Option<ChatCompletionChunkFunctionCall>,

    /// The refusal message generated by the model.
    ///
    /// 模型生成的拒绝回答信息。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub refusal: Option<StaticRefStr>,
}

/// A tool call chunk object within a streamed delta.
///
/// 流式增量中的工具调用 Chunk 对象。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionChunkToolCall {
    /// The index of the tool call in the tool_calls array.
    ///
    /// 工具调用在 tool_calls 数组中的索引。
    pub index: u32,

    /// The ID of the tool call.
    ///
    /// 工具调用的 ID。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<StaticRefStr>,

    /// The type of the tool (e.g., "function").
    ///
    /// 工具的类型（例如 "function"）。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#type: Option<StaticRefStr>,

    /// Function call details in this chunk.
    ///
    /// 当前 Chunk 中的函数调用详情。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function: Option<ChatCompletionChunkFunction>,
}

/// Deprecated function call details in a streamed chunk.
///
/// 流式 Chunk 中的函数调用详情（已废弃）。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionChunkFunctionCall {
    /// The name of the function to call.
    ///
    /// 要调用的函数名称。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<StaticRefStr>,

    /// The arguments to call the function with.
    ///
    /// 调用函数传入的增量参数。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<StaticRefStr>,
}

/// Function details in a tool call chunk.
///
/// 工具调用 Chunk 中的函数详情。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionChunkFunction {
    /// The name of the function to call.
    ///
    /// 要调用的函数名称。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<StaticRefStr>,

    /// The arguments to call the function with.
    ///
    /// 调用函数传入的增量参数。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<StaticRefStr>,
}
