use ref_str::StaticRefStr;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

use super::{
    agent::AgentConfig,
    content::{AudioContent, ImageContent, VideoContent},
    request::{GenerationConfig, SafetySetting, ServiceTier},
    step::Step,
    tool::Tool,
    webhook::WebhookConfig,
};

/// Interaction resource object returned by Gemini Interactions API.
///
/// Gemini Interactions API 返回的 Interaction 资源对象。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Interaction {
    /// Unique identifier for the interaction completion.
    ///
    /// Interaction 完成的唯一标识符。
    pub id: String,
    /// Object type, always "interaction".
    ///
    /// 对象类型，恒为 "interaction"。
    #[serde(default = "default_object")]
    pub object: String,
    /// Required. Status of the interaction.
    ///
    /// 必填。Interaction 的状态。
    pub status: InteractionStatus,
    /// Model name used for generating interaction.
    ///
    /// 用于生成 Interaction 的模型名称。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<StaticRefStr>,
    /// Agent name used for generating interaction.
    ///
    /// 用于生成 Interaction 的 Agent 名称。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent: Option<StaticRefStr>,
    /// Steps that make up the interaction.
    ///
    /// 构成 Interaction 的步骤列表。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<Step>>,
    /// Statistics on interaction token usage.
    ///
    /// Interaction Token 使用量统计。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<Usage>,
    /// Concatenated text from last model output (added by SDK/helper).
    ///
    /// 来自最新模型输出的拼接文本（由 SDK 辅助添加）。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_text: Option<String>,
    /// Last image generated by model.
    ///
    /// 模型生成的最新图像。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_image: Option<ImageContent>,
    /// Last audio generated by model.
    ///
    /// 模型生成的最新音频。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_audio: Option<AudioContent>,
    /// Last video generated by model.
    ///
    /// 模型生成的最新视频。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_video: Option<VideoContent>,
    /// Environment ID for interaction.
    ///
    /// Interaction 的环境 ID。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub environment_id: Option<String>,
    /// Time created in ISO 8601 format.
    ///
    /// ISO 8601 格式的创建时间。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Time last updated in ISO 8601 format.
    ///
    /// ISO 8601 格式的最近更新时间。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
    /// System instruction.
    ///
    /// 系统指令。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_instruction: Option<String>,
    /// Tools declaration.
    ///
    /// 工具声明列表。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<Tool>>,
    /// Generation config.
    ///
    /// 生成配置。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generation_config: Option<GenerationConfig>,
    /// Agent config.
    ///
    /// Agent 配置。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_config: Option<AgentConfig>,
    /// Environment config.
    ///
    /// 环境配置。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub environment: Option<serde_json::Value>,
    /// Labels.
    ///
    /// 标签。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub labels: Option<HashMap<String, String>>,
    /// ID of previous interaction.
    ///
    /// 上一个 Interaction 的 ID。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub previous_interaction_id: Option<String>,
    /// Response format.
    ///
    /// 响应格式。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_format: Option<serde_json::Value>,
    /// Response modalities.
    ///
    /// 响应模态。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_modalities: Option<Vec<ResponseModality>>,
    /// Safety settings.
    ///
    /// 安全设置。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub safety_settings: Option<Vec<SafetySetting>>,
    /// Service tier.
    ///
    /// 服务层级。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<ServiceTier>,
    /// Webhook config.
    ///
    /// Webhook 配置。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub webhook_config: Option<WebhookConfig>,
}

fn default_object() -> String {
    "interaction".to_string()
}

/// Status of the interaction.
///
/// Interaction 的状态。
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum InteractionStatus {
    InProgress,
    RequiresAction,
    Completed,
    Failed,
    Cancelled,
    Incomplete,
    BudgetExceeded,
    Queued,
}

/// Token usage statistics for interaction.
///
/// Interaction Token 使用量统计。
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub struct Usage {
    /// Number of tokens in prompt context.
    ///
    /// 提示词上下文中的 Token 数量。
    #[serde(default)]
    pub total_input_tokens: i32,
    /// Total number of output tokens generated.
    ///
    /// 生成的所有响应中的输出 Token 总数。
    #[serde(default)]
    pub total_output_tokens: i32,
    /// Number of tokens of thoughts for thinking models.
    ///
    /// 思考模型的思考 Token 数量。
    #[serde(default)]
    pub total_thought_tokens: i32,
    /// Number of tokens in cached content.
    ///
    /// 缓存内容中的 Token 数量。
    #[serde(default)]
    pub total_cached_tokens: i32,
    /// Number of tokens in tool use prompts.
    ///
    /// 工具使用提示中的 Token 数量。
    #[serde(default)]
    pub total_tool_use_tokens: i32,
    /// Total token count.
    ///
    /// 总 Token 数量。
    #[serde(default)]
    pub total_tokens: i32,
    /// Token breakdown by modality for input.
    ///
    /// 输入部分的按模态划分的 Token 使用量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_tokens_by_modality: Option<Vec<ModalityTokens>>,
    /// Token breakdown by modality for output.
    ///
    /// 输出部分的按模态划分的 Token 使用量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_tokens_by_modality: Option<Vec<ModalityTokens>>,
    /// Token breakdown by modality for cached tokens.
    ///
    /// 缓存 Token 的按模态划分使用量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cached_tokens_by_modality: Option<Vec<ModalityTokens>>,
    /// Token breakdown by modality for tool-use.
    ///
    /// 工具使用的按模态划分 Token 使用量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_use_tokens_by_modality: Option<Vec<ModalityTokens>>,
    /// Grounding tool count breakdown.
    ///
    /// 依据工具数量明细。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub grounding_tool_count: Option<Vec<GroundingToolCount>>,
}

/// Token count for a single modality.
///
/// 单个模态的 Token 计数。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModalityTokens {
    /// Modality type ('text', 'image', 'audio', 'video', 'document').
    ///
    /// 模态类型（'text', 'image', 'audio', 'video', 'document'）。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub modality: Option<ResponseModality>,
    /// Number of tokens.
    ///
    /// Token 数量。
    #[serde(default)]
    pub tokens: i32,
}

/// Grounding tool count.
///
/// 依据工具计数。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GroundingToolCount {
    /// Grounding tool type ('google_search', 'google_maps', 'retrieval').
    ///
    /// 依据工具类型（'google_search', 'google_maps', 'retrieval'）。
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub tool_type: Option<StaticRefStr>,
    /// Count.
    ///
    /// 数量。
    #[serde(default)]
    pub count: i32,
}

/// Response modality types.
///
/// 响应模态类型。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ResponseModality {
    Text,
    Image,
    Audio,
    Video,
    Document,
}

/// Resolution of media content.
///
/// 媒体内容的分辨率。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum MediaResolution {
    Low,
    Medium,
    High,
    UltraHigh,
}

/// Logical error model (gRPC/REST Status).
///
/// 逻辑错误模型（gRPC/REST 状态）。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Status {
    /// Status code (enum of google.rpc.Code).
    ///
    /// 状态码。
    pub code: i32,
    /// Developer-facing error message.
    ///
    /// 面向开发者的错误消息。
    pub message: String,
    /// Detailed error payload messages.
    ///
    /// 详细错误载荷消息列表。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<Vec<serde_json::Value>>,
}

/// Empty response object for deletions.
///
/// 删除操作的空响应对象。
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct DeleteInteractionResponse {}
