use ref_str::StaticRefStr;
use serde::{Deserialize, Serialize};

/// The base structured datatype containing multi-part content of a message.
///
/// 包含消息的多部分内容的基础结构化数据类型。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Content {
    /// Ordered `Parts` that constitute a single message.
    ///
    /// 构成单个消息的有序 `Parts`。
    pub parts: Vec<Part>,
    /// Optional. The producer of the content. Must be either 'user' or 'model'.
    ///
    /// 可选。内容的生产者。必须是 'user' 或 'model'。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<StaticRefStr>,
}

impl Content {
    pub fn user(parts: Vec<Part>) -> Self {
        Self {
            parts,
            role: Some("user".into()),
        }
    }

    pub fn model(parts: Vec<Part>) -> Self {
        Self {
            parts,
            role: Some("model".into()),
        }
    }
}

/// A datatype containing media that is part of a multi-part `Content` message.
///
/// 包含多部分 `Content` 消息一部分的媒体的数据类型。
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Part {
    /// Inline text.
    ///
    /// 内联文本。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,

    /// Inline media bytes.
    ///
    /// 内联媒体字节。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inline_data: Option<Blob>,

    /// A predicted [FunctionCall] returned from the model that contains
    /// a string representing the [FunctionDeclaration.name] with the
    /// arguments and their values.
    ///
    /// 模型返回的预测 [FunctionCall]，包含表示 [FunctionDeclaration.name] 的字符串以及参数及其值。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_call: Option<FunctionCall>,

    /// The result output of a [FunctionCall] that contains a string
    /// representing the [FunctionDeclaration.name] and a structured
    /// JSON object containing any output from the function call.
    ///
    /// [FunctionCall] 的结果输出，包含表示 [FunctionDeclaration.name] 的字符串和包含函数调用输出的结构化 JSON 对象。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_response: Option<FunctionResponse>,

    /// URI based data.
    ///
    /// 基于 URI 的数据。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_data: Option<FileData>,

    /// Code generated by the model that is meant to be executed.
    ///
    /// 模型生成的旨在执行的代码。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub executable_code: Option<ExecutableCode>,

    /// Result of executing the [ExecutableCode].
    ///
    /// 执行 [ExecutableCode] 的结果。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code_execution_result: Option<CodeExecutionResult>,

    /// Indicates if the part is thought content.
    ///
    /// 指示该部分是否为思考内容。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thought: Option<bool>,

    /// Signature of the thought content.
    ///
    /// 思考内容的签名。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thought_signature: Option<StaticRefStr>,

    /// Metadata for video content.
    ///
    /// 视频内容的元数据。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_metadata: Option<VideoMetadata>,

    /// Custom metadata associated with the Part.
    ///
    /// 与 Part 关联的自定义元数据。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_metadata: Option<serde_json::Value>,
}

impl Part {
    pub fn text(text: impl Into<String>) -> Self {
        Self {
            text: Some(text.into()),
            ..Default::default()
        }
    }
}

/// Metadata for video content.
///
/// 视频内容的元数据。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoMetadata {
    /// Start offset of the video.
    ///
    /// 视频的起始偏移量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_offset: Option<StaticRefStr>,

    /// End offset of the video.
    ///
    /// 视频的结束偏移量。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_offset: Option<StaticRefStr>,
}

/// Raw media bytes.
///
/// 原始媒体字节。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Blob {
    /// The IANA standard MIME type of the source data.
    ///
    /// 源数据的 IANA 标准 MIME 类型。
    #[serde(rename = "mime_type")]
    pub mime_type: StaticRefStr,
    /// Raw bytes for media formats.
    ///
    /// 媒体格式的原始字节。
    pub data: StaticRefStr, // Base64 encoded string
}

/// A predicted [FunctionCall] returned from the model.
///
/// 模型返回的预测 [FunctionCall]。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCall {
    /// Optional. The unique id of the function call.
    ///
    /// 可选。函数调用的唯一 ID。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<StaticRefStr>,
    /// The name of the function to call.
    ///
    /// 要调用的函数的名称。
    pub name: StaticRefStr,
    /// The function parameters and values in JSON format.
    ///
    /// JSON 格式的函数参数和值。
    pub args: serde_json::Value,
}

/// The result output of a [FunctionCall].
///
/// [FunctionCall] 的结果输出。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionResponse {
    /// Optional. The id of the function call this response is for.
    ///
    /// 可选。此响应所针对的函数调用的 ID。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<StaticRefStr>,
    /// The name of the function to call.
    ///
    /// 要调用的函数的名称。
    pub name: StaticRefStr,
    /// The function response in JSON format.
    ///
    /// JSON 格式的函数响应。
    pub response: serde_json::Value,
    /// Optional. Ordered Parts that constitute a function response.
    ///
    /// 可选。构成函数响应的有序 Parts。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parts: Option<Vec<FunctionResponsePart>>,
    /// Optional. Signals that function call continues.
    ///
    /// 可选。表示函数调用继续。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub will_continue: Option<bool>,
    /// Optional. Specifies how the response should be scheduled.
    ///
    /// 可选。指定如何调度响应。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduling: Option<Scheduling>,
}

/// A datatype containing media that is part of a `FunctionResponse` message.
///
/// 包含 `FunctionResponse` 消息一部分的媒体的数据类型。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FunctionResponsePart {
    /// Inline media bytes.
    ///
    /// 内联媒体字节。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inline_data: Option<FunctionResponseBlob>,
}

/// Raw media bytes for function response.
///
/// 函数响应的原始媒体字节。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionResponseBlob {
    /// The IANA standard MIME type of the source data.
    ///
    /// 源数据的 IANA 标准 MIME 类型。
    #[serde(rename = "mime_type")]
    pub mime_type: StaticRefStr,
    /// Raw bytes for media formats.
    ///
    /// 媒体格式的原始字节。
    pub data: StaticRefStr, // Base64 encoded string
}

/// Specifies how the response should be scheduled in the conversation.
///
/// 指定如何在对话中调度响应。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Scheduling {
    SchedulingUnspecified,
    Silent,
    WhenIdle,
    Interrupt,
}

/// URI based data.
///
/// 基于 URI 的数据。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileData {
    /// Optional. The IANA standard MIME type of the source data.
    ///
    /// 可选。源数据的 IANA 标准 MIME 类型。
    #[serde(rename = "mime_type", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<StaticRefStr>,
    /// Required. The URI of the source data.
    ///
    /// 必填。源数据的 URI。
    #[serde(rename = "file_uri")]
    pub file_uri: StaticRefStr,
}

/// Code generated by the model that is meant to be executed.
///
/// 模型生成的旨在执行的代码。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutableCode {
    /// Required. The language of the code.
    ///
    /// 必填。代码的语言。
    pub language: CodeLanguage,
    /// Required. The code to be executed.
    ///
    /// 必填。要执行的代码。
    pub code: StaticRefStr,
}

/// Supported languages for code execution.
///
/// 代码执行支持的语言。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CodeLanguage {
    LanguageUnspecified,
    Python,
}

/// Result of executing the [ExecutableCode].
///
/// 执行 [ExecutableCode] 的结果。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CodeExecutionResult {
    /// Required. Outcome of the code execution.
    ///
    /// 必填。代码执行的结果。
    pub outcome: CodeExecutionOutcome,
    /// Optional. Contains stdout when code execution is successful, or
    /// stderr when code execution unsuccessful.
    ///
    /// 可选。代码执行成功时包含 stdout，或代码执行失败时包含 stderr。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output: Option<StaticRefStr>,
}

/// Outcome of the code execution.
///
/// 代码执行的结果。
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CodeExecutionOutcome {
    OutcomeUnspecified,
    OutcomeOk,
    OutcomeFailed,
    OutcomeDeadlineExceeded,
}

/// Content Part modality
///
/// 内容部分模态
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Modality {
    ModalityUnspecified,
    Text,
    Image,
    Video,
    Audio,
    Document,
}
